# Generated by Django 2.2 on 2019-11-16 11:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20191116_1035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Review',
        ),
    ]
